### ISSUE TITLE
Hess - check role was supposed to be set to “test” on VOEvents for development. 

### ISSUE THREAD

**Issue by Dylanb-dev** [ADACS-Australia/mwa_trigger#104] opened 2023-01-18 03:52 UTC
- [x] What is happening with Hess currently - Currently scheduled to send test and real events to tracet, tracet tested to be working with hess events

- [x] Test Hess events come through the system and can be used in test proposals - Can do this now, and events will be grouped with swift events if they are referenced
- [x] Hess sends through role="test" events that can be used in proposals, currently they just send role="observation".

**Comment by PaulHancock** [comment] 2023-01-18 05:57
When we receive events from HESS that have been marked as test events they should not be ignored.
Instead they should be sent through the normal observing logic and if a descision is made to observe then the observing request should have `pretend=True` (MWA) or the ATCA equivalent.
This will mean that we can use test events to confirm that our observing logic is behaving as intended.

**Comment by Dylanb-dev** [comment] 2023-01-30 07:54
Hess reference swift for followup which can be used to group events.
![image](https://user-images.githubusercontent.com/9392694/215419031-4a6d8f2f-6fde-4248-bd00-478a108b0bd8.png)

**Closed as completed** 2023-02-08 01:59 UTC
Labels: Low Priority
